# Generated by Django 5.2.2 on 2025-06-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='COD', max_length=50, null=True),
        ),
    ]
