# Generated by Django 5.2.2 on 2025-06-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_payment_method'),  # Thay bằng migration hợp lệ nhất trước merge
        ('shop', '0001_initial'),
    ]

    operations = [
    ]
